### ISSUE TITLE
[satellite] white spaces in org name

### ISSUE THREAD

**Issue by masatake** [ssato/miniascape-templates#7]
If satellite.organization contains a whitespace like "example com", --foreman-initial-organization option doen's work expectedly because satellite-installer receives two arguments " --foreman-initial-organization=example" and "com". What we would like to pass is  "--foreman-initial-organization=example com".
As far as I know, there is not simple way to avoid this in a classical shell feature.

Howerver, you use bash for writing config.sh. So we can use array to store the option and arguments.
Is using array for solving this issue acceptable?

**Comment by ssato** [comment]
Using bash array feels too much for me. Shell script is a temporal solution and I think that it should be implemented with using ansible instead.

**Comment by masatake** [comment]
I see.
